image: rvillegasvalera/qa-java24-browsers:latest

pipelines:
  custom:
    # === Pipeline para ejecutar una suite específica ===
    Run Suite:
      - variables:
          - name: SUITE
            default: "UiTest"
            allowed-values:
              - "ApiTest"
              - "ArticlesTest"
              - "AssociatedDimensionsTest"
              - "AssociatedUnitArticleFlowTest"
              - "BusinessDimensionsTest"
              - "ConfigurationTest"
              - "ForecastingConceptsTest"
              - "ForecastsTest"
              - "InventoryLocationsTest"
              - "ListOfMaterialsTest"
              - "ProductionPlanTest"
              - "PruebasTest"
              - "PurchasePlanTest"
              - "UiTest"
              - "UnitTest"
              - "ProjectionOfStockNeedsTest"
              - "InventoryHealthTest"
              - "SubstituteProductsTest"
              - "ForecastedMaterialRequirementsTest"
              - "TrackingChangesInTheSameCycleTest"
              - "TrackingChangesBetweenCyclesTest"
              - "CommercialBudgetTest"
              - "SalesHistoryTest"
              - "PendingOrdersTest"
              - "ForecastAnalysisListTest"
              - "PotentialDiscontinuedTest"
              - "PotentialLaunchesTest"
              - "InventoryTest"
              - "MpsMrpReportTest"
              - "SupplierMaterialListTest"
              - "PurchaseAlertsTest"
              - "ProcessConfigListTest"
              - "ProductionAlertsTest"
              - "ProductionTest"
              - "ProductionSequencingTest"
          - name: USER
            default: "rvillegas"
            allowed-values:
              - "rvillegas"
              - "lnieves"
              - "test2"
          - name: BROWSER
            default: "edge"
            allowed-values:
              - "edge"
              - "chrome"
          - name: ENVIRONMENT
            default: ""
          - name: KEYCLIENT
            default: ""
      - step:
          name: Restaurar BD (opcional por KEYCLIENT)
          caches:
            - maven
          script:
            - |
              if [[ -n "${KEYCLIENT:-}" ]]; then
                mvn -q -DskipTests=false -Dtest=config.RecoverDbTest -DfailIfNoTests=false -Dkeyclient="${KEYCLIENT}" test
              else
                echo "[restore] KEYCLIENT no informado; se omite restauración."
              fi
          artifacts:
            - target/logs/*.log

      - step:
          name: Ejecutando pruebas
          size: 4x
          caches:
            - maven
          script:
            - echo "Ejecutar pruebas..."
            - bash scripts/run-suite.sh $SUITE
          artifacts:
            - target/*.html
            - target/*.json
            - target/logs/*.log
            - target/screenshots/**

    # === Pipeline para ejecutar la regresión completa ===
    Run Regression Suite:
      - variables:
          - name: USER
            default: "rvillegas"
            allowed-values:
              - "rvillegas"
              - "lnieves"
              - "test2"
          - name: BROWSER
            default: "edge"
            allowed-values:
              - "edge"
              - "chrome"
          - name: ENVIRONMENT
            default: ""
          - name: KEYCLIENT
            default: ""
      - step:
          name: Restaurar BD (opcional por KEYCLIENT)
          caches:
            - maven
          script:
            - |
              if [[ -n "${KEYCLIENT:-}" ]]; then
                mvn -q -DskipTests=false -Dtest=config.RecoverDbTest -DfailIfNoTests=false -Dkeyclient="${KEYCLIENT}" test
              else
                echo "[restore] KEYCLIENT no informado; se omite restauración."
              fi
          artifacts:
            - target/logs/*.log

      - parallel:
          - step:
              name: "ArticlesTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh ArticlesTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "AssociatedDimensionsTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh AssociatedDimensionsTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "AssociatedUnitArticleFlowTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh AssociatedUnitArticleFlowTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "BusinessDimensionsTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh BusinessDimensionsTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "ForecastingConceptsTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh ForecastingConceptsTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "CalculationTests"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas de cálculo en orden..."
                - bash scripts/run-suite.sh ConfigurationTest
                - bash scripts/run-suite.sh ForecastsTest
                - bash scripts/run-suite.sh PurchasePlanTest
                - bash scripts/run-suite.sh ProductionPlanTest
                - bash scripts/run-suite.sh InventoryHealthTest
                - bash scripts/run-suite.sh ProjectionOfStockNeedsTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "ListOfMaterialsTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh ListOfMaterialsTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "UnitTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh UnitTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "InventoryLocationsTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh InventoryLocationsTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "SubstituteProductsTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh SubstituteProductsTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "ForecastedMaterialRequirementsTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh ForecastedMaterialRequirementsTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "TrackingChangesInTheSameCycleTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh TrackingChangesInTheSameCycleTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "TrackingChangesBetweenCyclesTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh TrackingChangesBetweenCyclesTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**
                -

          - step:
              name: "CommercialBudgetTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh CommercialBudgetTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "SalesHistoryTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh SalesHistoryTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "PendingOrdersTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh PendingOrdersTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "ForecastAnalysisListTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh ForecastAnalysisListTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "PotentialDiscontinuedTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh PotentialDiscontinuedTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "PotentialLaunchesTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh PotentialLaunchesTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "InventoryTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh InventoryTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**
          - step:
              name: "MpsMrpReportTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh MpsMrpReportTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "SupplierMaterialListTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh SupplierMaterialListTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

          - step:
              name: "PurchaseAlertsTest"
              size: 4x
              caches:
                - maven
              script:
                - echo "Ejecutar pruebas..."
                - bash scripts/run-suite.sh PurchaseAlertsTest
              artifacts:
                - target/*.html
                - target/*.json
                - target/logs/*.log
                - target/screenshots/**

                - step:
                    name: "ProcessConfigListTest"
                    size: 4x
                    caches:
                      - maven
                    script:
                      - echo "Ejecutar pruebas..."
                      - bash scripts/run-suite.sh ProcessConfigListTest
                    artifacts:
                      - target/*.html
                      - target/*.json
                      - target/logs/*.log
                      - target/screenshots/**

                - step:
                    name: "ProductionAlertsTest"
                    size: 4x
                    caches:
                      - maven
                    script:
                      - echo "Ejecutar pruebas..."
                      - bash scripts/run-suite.sh ProductionAlertsTest
                    artifacts:
                      - target/*.html
                      - target/*.json
                      - target/logs/*.log
                      - target/screenshots/**

                - step:
                    name: "ProductionTest"
                    size: 4x
                    caches:
                      - maven
                    script:
                      - echo "Ejecutar pruebas..."
                      - bash scripts/run-suite.sh ProductionTest
                    artifacts:
                      - target/*.html
                      - target/*.json
                      - target/logs/*.log
                      - target/screenshots/**

                - step:
                    name: "ProductionSequencingTest"
                    size: 4x
                    caches:
                      - maven
                    script:
                      - echo "Ejecutar pruebas..."
                      - bash scripts/run-suite.sh ProductionSequencingTest
                    artifacts:
                      - target/*.html
                      - target/*.json
                      - target/logs/*.log
                      - target/screenshots/**